version: "3.8"
services:
  db:
    build: ./db
    image: "uniphone-webdb"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: uniphone_db
    restart: always
    container_name: "uniphone-db"
  web:
    build: .
    image: "uniphone-webapp"
    environment:
      MYSQL_DATABASE: uniphone_db
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: db
    ports:
      - "3000:8080"
    depends_on:
      - db
    restart: on-failure
    container_name: "uniphone-app"