apiVersion: apps/v1
kind: Deployment
metadata:
  name: uniphone-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uniphone-db
  template:
    metadata:
      labels:
        app: uniphone-db
    spec:
      containers:
      - name: uniphone-db
        image: kevin0506/dbserver
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: MYSQL_DATABASE
          value: uniphone_db
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: uniphone-db
spec:
  selector:
    app: uniphone-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306